### ISSUE TITLE
No releases created for `schubert_dances`

### ISSUE THREAD

**Issue by johentsch** [DCMLab/annotation_workflow_template#13]
Actually this seems to be two issues:

1. The [first attempt](https://github.com/DCMLab/schubert_dances/actions/runs/6713183027/job/18244245612#step:5:21) to release a new version release for `schubert_dances` stopped in the middle, apparently because none of the files needed to be updated with a new version number: Only the README existed and it did not contain the current version number at that point. Committing the changes therefore failed.
2. For the [second attempt](https://github.com/DCMLab/schubert_dances/actions/runs/6714315149/job/18247354756) I had added the version number and it ran through but somehow the release was not created.

**Comment by marcelmmc** [comment]
Hi @johentsch. Oh, sorry, the workflow does not stop even if no files were modified during the update. In fact, the first attempt was able to trigger the action to create the release. I think the problem could be related to a security rule in [schubert_dances](https://github.com/DCMLab/schubert_dances). I forked this repository, and I was able to generate a [release](https://github.com/marcelmmc/schubert_dances/releases/tag/v2.2). Could you please grant me admin rights to check the rules of this?

**Comment by johentsch** [comment]
Turns out the releases are there, found them by heading to https://github.com/DCMLab/schubert_dances/releases/ I found the setting close to where the homepage URL is displayed.
